name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: composer-normalize-action
        uses: localheinz/composer-normalize-action@0.5.2

  test-matrix:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        php-versions: ['7.4', '8.0']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, xdebug #optional
          ini-values-csv: post_max_size=256M, short_open_tag=On #optional
          coverage: xdebug #optional
      - name: Check PHP Version
        run: php -v
      - name: Check Composer Version
        run: composer -V
      - name: Install Composer Dependencies
        run: composer install
      - name: PHPUnit Tests
        run: composer test
